### PR TITLE
Add HTML result viewer

### PR DESCRIPTION
**Pull request by msrb**
This is a rpminspect-inspired result viewer that should make it easier for people to review installability results.

### CODE REVIEW

**Comment by msrb** [comment]
Example (internal URL): http://artifacts.osci.redhat.com/testing-farm/7c853fdb-420c-4223-af00-5490496870cc/work-installability4g400us1/installability/execute/data/installability/data/viewer.html

**Comment by msrb** [comment]
@Andrei-Stepanov WDYT?

**Comment by msrb** [comment]
This is just adding the viewer to the package, i.e. not modifying installability itself. The risk of breaking anything is pretty much non-existent here. Let's merge this :)

**Comment by AdamWill** [comment]
what needs to be done for this to be used in Fedora CI? the current result format for installability is not great. If we'd had this viewer I think it would have made it much clearer to folks why [tests were failing due to AVCs](https://bugzilla.redhat.com/show_bug.cgi?id=2250930) recently.

**Pull request merged**
